const projects = [
  {
    id: 'project1',
    title: 'AI / ML Solutions & Neural Vision',
    slug: 'ai-ml-solutions',
    category: 'Intelligent AI & Vision',
    categorySlug: 'ai-ml',
    tagline: 'Deep learning models, computer vision & predictive neural pipelines.',
    handwritingNote: 'Math made visual — trained on real data with high precision.',
    img: '/project1/project1.webp',
    link: '/projects/project1',
    company: 'Homies Creator Studio',
    liveLink: 'https://demo-ai.homiesstudio.com',
    price: 2999,
    originalPrice: 5999,
    rating: 4.96,
    reviewCount: 42,
    salesCount: 168,
    difficulty: 'Intermediate',
    projectType: 'AI/ML Model & Web Interface',
    platform: 'Web & Cloud Server',
    language: 'Python 3.10+',
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    creator: {
      name: 'Homies AI Research Labs',
      handle: '@homies_ai',
      role: 'Verified Deep Learning Architect',
      rating: 4.98,
      sales: 520,
      avatar: '/homies/header-logo.png',
      responseTime: '< 1 hour',
      badges: ['Verified Creator', 'Top Seller', 'Fast Support'],
    },
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Applied machine learning models, intelligent computer vision, and predictive AI systems built to solve complex real-world tasks.',
      'Optimized architectures with seamless REST API integrations and intuitive user interfaces for live inference.',
      'Comprehensive evaluation metrics, confusion matrices, and interactive web demos ready for deployment and academic review.',
    ],
    whyHomies: [
      'Trained on verified benchmark datasets with transparent evaluation curves, ROC metrics, and zero data leakage.',
      'No black-box confusion: we provide crystal-clear explanations of model architecture, loss functions, and weight tuning.',
      'Turnkey deployment with modern web interfaces (Streamlit / FastAPI / Next.js) for instant live inference.',
    ],
    whatMakesUsSpecial: [
      'Exhaustive exploratory data analysis (EDA) and robust feature engineering pipelines with reproducible notebooks.',
      'Comparative benchmarking across multiple baseline models demonstrating state-of-the-art accuracy.',
      'IEEE research paper format ready reports with high-resolution training loss and accuracy plots.',
      'One-on-one presentation coaching and mathematical intuition breakdown for flawless project defense.',
    ],
    deliverables: [
      'Trained PyTorch & TensorFlow Model Weights (.pt / .h5 / .onnx)',
      'Clean, Documented Jupyter Notebooks & Data Preprocessing Scripts',
      'Interactive Live Inference Web Application (FastAPI + Streamlit / Next.js)',
      'IEEE-Standard Synopsis, 40+ Page Thesis Report & Presentation Deck',
    ],
    deliverableFiles: [
      { name: 'Source Code & Model Weights (ZIP)', size: '142.5 MB', type: 'code' },
      { name: 'IEEE Format Thesis Report (PDF)', size: '6.4 MB', type: 'pdf' },
      { name: 'Model Architecture Diagrams (PNG/SVG)', size: '2.8 MB', type: 'diagram' },
      { name: 'Training Datasets & EDA Notebooks (ZIP)', size: '85.2 MB', type: 'db' },
      { name: 'Defense Presentation Deck (PPTX)', size: '12.1 MB', type: 'ppt' },
      { name: 'Full Video Demo & Code Walkthrough (MP4)', size: '198 MB', type: 'video' },
    ],
    requirements: {
      os: 'Windows 10/11, macOS (Apple Silicon supported), Ubuntu Linux 20.04+',
      software: 'Python 3.10+, CUDA 11.8+ (optional for GPU acceleration), VS Code',
      hardware: 'Minimum 8 GB RAM (16 GB recommended), 4 GB free disk space',
      dependencies: 'PyTorch, Torchvision, OpenCV, Scikit-Learn, FastAPI, Streamlit, Pandas, NumPy',
      installationSteps: [
        'Unzip the downloaded project archive to your project workspace.',
        'Create a virtual environment: python -m venv venv && source venv/bin/activate (or venv\\Scripts\\activate on Windows).',
        'Install required packages: pip install -r requirements.txt',
        'Launch the web inference app: streamlit run app.py (or uvicorn api:app --reload)',
      ],
    },
    reviews: [
      {
        id: 'rev-101',
        user: 'Vikramaditya K.',
        role: 'AI Researcher & Final Year CSE',
        rating: 5,
        date: '3 days ago',
        verified: true,
        comment:
          'The model weights achieved 97.4% precision on test data without any overfitting. The IEEE paper template and architecture schematics got me direct approval from my faculty committee.',
      },
      {
        id: 'rev-102',
        user: 'Sneha Roy',
        role: 'Machine Learning Engineer',
        rating: 5,
        date: '2 weeks ago',
        verified: true,
        comment: 'Extremely modular code! The FastAPI endpoints were plug-and-play with our internal dashboard. Saved our team at least 40 hours of pipeline setup.',
      },
    ],
    license: 'Full Academic Defense & Commercial SaaS License',
    techStack: ['PyTorch', 'TensorFlow', 'OpenCV', 'Scikit-Learn', 'YOLO / Transformers', 'Pandas', 'FastAPI', 'Streamlit'],
  },
  {
    id: 'project2',
    title: 'Web & Full Stack Ecosystems',
    slug: 'web-full-stack',
    category: 'Full-Stack & Mobile',
    categorySlug: 'web-dev',
    tagline: 'High-performance websites, mobile apps & interactive web experiences.',
    handwritingNote: 'Pixel-perfect code crafted with smooth, modern animations.',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    company: 'Homies Creator Studio',
    liveLink: 'https://demo-web.homiesstudio.com',
    price: 3499,
    originalPrice: 6999,
    rating: 4.94,
    reviewCount: 36,
    salesCount: 145,
    difficulty: 'Intermediate',
    projectType: 'Full-Stack Application',
    platform: 'Web & Mobile (Cross-platform)',
    language: 'TypeScript / JavaScript',
    isFeatured: true,
    isBestSeller: true,
    isTrending: false,
    creator: {
      name: 'Homies Web Architecture Lab',
      handle: '@homies_web',
      role: 'Senior Full-Stack Architect',
      rating: 4.95,
      sales: 410,
      avatar: '/homies/header-logo.png',
      responseTime: '< 2 hours',
      badges: ['Verified Creator', 'Production Ready', 'Clean Architecture'],
    },
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'High-performance full-stack web applications, cross-platform mobile apps, and fluid animated web platforms.',
      'Modern responsive design with pixel-perfect execution, server-side rendering, and robust database architecture.',
      'Engineered from wireframing and prototyping to production deployment with continuous integration and automated backups.',
    ],
    whyHomies: [
      'Award-winning visual aesthetics paired with industry-grade, clean architecture and sub-second page loads.',
      'Responsive across all screen sizes with fluid 60fps animations and accessible, SEO-optimized semantic markup.',
      'Complete authentication, database models, payment gateways, role-based access control, and admin consoles included.',
    ],
    whatMakesUsSpecial: [
      'Cutting-edge frontend stack (Next.js 14, Three.js, GSAP, Tailwind / SCSS) for unforgettable user journeys.',
      'Scalable PostgreSQL database schema with Prisma ORM migrations and automated indexing.',
      '100% full source code ownership with modular folder structures and comprehensive setup documentation.',
      'One-click deployment guides for Vercel, AWS, Docker, and Supabase.',
    ],
    deliverables: [
      'Full-Stack Production Source Code (Frontend + Backend + DB Migrations)',
      'Live Deployed Web URL & Mobile APK / React Native Bundle',
      'Responsive Design System & Reusable Component Library',
      'Comprehensive Architecture, API Spec & Setup Documentation',
    ],
    deliverableFiles: [
      { name: 'Complete Next.js Source Code (ZIP)', size: '38.2 MB', type: 'code' },
      { name: 'Database Schemas & Prisma Migrations (SQL)', size: '2.1 MB', type: 'db' },
      { name: 'API Documentation & Postman Collection (JSON)', size: '1.4 MB', type: 'doc' },
      { name: 'UI Component Library & Figma Tokens', size: '14.5 MB', type: 'diagram' },
      { name: 'Deployment & Setup Walkthrough (PDF)', size: '4.8 MB', type: 'pdf' },
    ],
    requirements: {
      os: 'Windows, macOS, Linux',
      software: 'Node.js 18.x+, npm / yarn / pnpm, Git, VS Code',
      hardware: '4 GB RAM minimum, 1 GB storage space',
      dependencies: 'Next.js 14, React 18, Prisma, PostgreSQL / Supabase, TailwindCSS, Lucide',
      installationSteps: [
        'Extract source code and navigate into project directory: cd homies-web-project',
        'Install all dependencies: npm install',
        'Copy .env.example to .env.local and configure database connection string.',
        'Run migrations: npx prisma migrate dev',
        'Start dev server: npm run dev and visit http://localhost:3000',
      ],
    },
    reviews: [
      {
        id: 'rev-201',
        user: 'Rohan Mehta',
        role: 'Startup Founder',
        rating: 5,
        date: '1 week ago',
        verified: true,
        comment: 'We launched our SaaS MVP in 4 days using this codebase. The auth flow, Stripe integration, and admin portal are flawlessly built.',
      },
    ],
    license: 'Commercial Unlimited Deployment License',
    techStack: ['React / Next.js', 'React Native', 'Node.js', 'TypeScript', 'Tailwind / SCSS', 'GSAP', 'Supabase / Firebase', 'PostgreSQL'],
  },
  {
    id: 'project3',
    title: 'IoT & Robotics Systems',
    slug: 'iot-robotics-systems',
    category: 'Hardware & Automation',
    categorySlug: 'iot-robotics',
    tagline: 'Bridging physical sensors with intelligent real-time automation.',
    handwritingNote: 'From circuit schematics to cloud control — built to work flawlessly.',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    company: 'Homies Creator Studio',
    liveLink: undefined,
    price: 3899,
    originalPrice: 7499,
    rating: 4.98,
    reviewCount: 54,
    salesCount: 192,
    difficulty: 'Advanced',
    projectType: 'Hardware & Software Prototype',
    platform: 'ESP32 / Microcontroller & Web Dashboard',
    language: 'C++ / Embedded C / Python',
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    creator: {
      name: 'Homies Embedded Robotics Core',
      handle: '@homies_robotics',
      role: 'Robotics & IoT Hardware Engineer',
      rating: 4.99,
      sales: 680,
      avatar: '/homies/header-logo.png',
      responseTime: '< 1 hour',
      badges: ['Hardware Verified', 'IEEE Certified', 'Live Lab Tested'],
    },
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Hardware-software integrated smart devices, robotics prototypes, and sensor-based automation systems with real-time cloud telemetry.',
      'Engineered from component selection and circuit schematic design through firmware development to interactive demonstration.',
      'Comprehensive oscilloscope testing and modular architecture built to ensure rock-solid hardware stability during live academic or industry reviews.',
    ],
    whyHomies: [
      'We build and test real, physical, working prototypes with full signal validation — zero simulated shortcuts.',
      'Comprehensive circuit debugging to ensure 100% stability during live college reviews and investor demos.',
      'Complete end-to-end guidance from breadboard wiring to custom PCB Gerber files and cloud telemetry dashboards.',
    ],
    whatMakesUsSpecial: [
      'Hands-on lab prototyping with verified sensor calibration & zero signal-loss pinout wiring.',
      'Modular architecture allowing rapid plug-and-play expansion and future sensor integration.',
      'Complete documentation including IEEE-format reports, block diagrams, and presentation PPTs.',
      'Live demonstration coaching with deep-dive technical viva question and answer preparation.',
    ],
    deliverables: [
      'Fully Tested Firmware & C++ Source Code (PlatformIO / Arduino IDE)',
      'High-Resolution Circuit Schematics, Pinouts & PCB Gerber Files',
      'Real-Time Web / Mobile Telemetry Dashboard (MQTT / Node-RED / React)',
      'Comprehensive Project Report (IEEE Format) & Defense PPT',
    ],
    deliverableFiles: [
      { name: 'Firmware & PlatformIO Source Code (ZIP)', size: '18.4 MB', type: 'code' },
      { name: 'PCB Gerber & EasyEDA Schematics (ZIP)', size: '6.2 MB', type: 'diagram' },
      { name: 'IEEE Format 50-Page Project Thesis (PDF)', size: '8.1 MB', type: 'pdf' },
      { name: 'Cloud Dashboard Code & MQTT Config', size: '12.8 MB', type: 'code' },
      { name: 'Circuit Wiring Guide & Pinout Diagram (High-Res)', size: '4.5 MB', type: 'diagram' },
      { name: 'Full Working Hardware Demo Video (MP4)', size: '240 MB', type: 'video' },
    ],
    requirements: {
      os: 'Windows, macOS, Linux',
      software: 'Arduino IDE 2.x or VS Code with PlatformIO, Python 3.9+',
      hardware: 'ESP32 / Arduino / Raspberry Pi, compatible sensor kit, USB-C data cable',
      dependencies: 'WiFi.h, PubSubClient, Adafruit Sensor Libraries, FreeRTOS',
      installationSteps: [
        'Open the project folder in VS Code with PlatformIO extension installed.',
        'Configure your WiFi credentials and MQTT broker IP in config.h',
        'Connect your ESP32 board via USB and click Upload & Monitor.',
        'Open the web dashboard to see real-time sensor streams and control relays.',
      ],
    },
    reviews: [
      {
        id: 'rev-301',
        user: 'Karthik Ramanathan',
        role: 'Robotics & Automation Lead',
        rating: 5,
        date: '5 days ago',
        verified: true,
        comment: 'The ESP32 FreeRTOS multitasking firmware ran with zero memory leaks. The circuit diagram and PCB Gerbers were accepted by our manufacturing lab on first try!',
      },
    ],
    license: 'Complete Academic Project & Hardware Prototyping License',
    techStack: ['ESP32', 'Arduino', 'Raspberry Pi', 'ROS', 'MQTT', 'Node-RED', 'FreeRTOS', 'Sensors & Actuators'],
  },
  {
    id: 'project4',
    title: 'Embedded & VLSI Design',
    slug: 'embedded-vlsi-design',
    category: 'Silicon & Digital Systems',
    categorySlug: 'embedded-vlsi',
    tagline: 'Precision digital logic, microcontroller architecture & synthesis.',
    handwritingNote: 'Silicon-grade logic verification with zero timing violations.',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    company: 'Homies Creator Studio',
    liveLink: undefined,
    price: 3199,
    originalPrice: 6499,
    rating: 4.95,
    reviewCount: 29,
    salesCount: 112,
    difficulty: 'Advanced',
    projectType: 'Research & Academic Build',
    platform: 'Xilinx FPGA & ARM Microcontroller',
    language: 'Verilog HDL / VHDL / C',
    isFeatured: false,
    isBestSeller: false,
    isTrending: true,
    creator: {
      name: 'Homies Silicon & VLSI Core',
      handle: '@homies_vlsi',
      role: 'VLSI RTL Design Engineer',
      rating: 4.96,
      sales: 310,
      avatar: '/homies/header-logo.png',
      responseTime: '< 3 hours',
      badges: ['Silicon Verified', 'Timing Clean', 'IEEE Paper Ready'],
    },
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Synthesizable RTL Verilog HDL and VHDL digital architectures, microcontroller firmware, and FPGA logic implementations.',
      'Comprehensive ModelSim testbench verification with exhaustive timing waveform analysis and state machine proofs.',
      'Tailored silicon-grade hardware modules engineered for academic excellence, thesis submission, and industrial tape-out standards.',
    ],
    whyHomies: [
      'Deep domain proficiency in RTL design, hardware description languages, and low-level firmware.',
      'Guaranteed synthesizable Verilog/VHDL code without inferring unwanted latches or setup/hold violations.',
      'Clear, understandable block-level breakdowns and State-Machine diagrams so you master every gate.',
    ],
    whatMakesUsSpecial: [
      'Complete testbenches with exhaustive test vector waveform simulations and coverage reports.',
      'Targeted FPGA bitstream generation & real-time board debugging on Xilinx / Altera development kits.',
      'Full reports with RTL schematics, power estimations, and area utilization tables.',
      'Comprehensive viva and interview preparation covering digital design fundamentals.',
    ],
    deliverables: [
      'Synthesizable Verilog HDL / VHDL RTL Code & Self-Checking Testbenches',
      'Simulation Waveforms (ModelSim/Questa) & RTL Gate Schematics',
      'Target FPGA Bitstream Files & STM32 / ARM Microcontroller Binaries',
      'Complete Project Thesis Report & Defense Presentation Deck',
    ],
    deliverableFiles: [
      { name: 'Synthesizable Verilog/VHDL Source & Testbenches (ZIP)', size: '9.8 MB', type: 'code' },
      { name: 'ModelSim / Vivado Simulation Waveforms (ZIP)', size: '24.1 MB', type: 'diagram' },
      { name: 'RTL Architecture & State Machine Diagrams (PDF)', size: '3.9 MB', type: 'diagram' },
      { name: 'Complete Academic Thesis Report (PDF)', size: '7.2 MB', type: 'pdf' },
      { name: 'Viva Voce Technical Question Bank & Solutions (PDF)', size: '2.5 MB', type: 'doc' },
    ],
    requirements: {
      os: 'Windows 10/11, Ubuntu Linux',
      software: 'Xilinx Vivado / ModelSim / Quartus Prime / Keil uVision',
      hardware: 'Min 8 GB RAM (16 GB for Vivado synthesis), 10 GB free disk space',
      dependencies: 'IEEE 1364-2001 Verilog Standard / IEEE 1076 VHDL Standard',
      installationSteps: [
        'Open Xilinx Vivado or ModelSim and create a new RTL project.',
        'Add the provided Verilog HDL files from the /src directory.',
        'Add the testbench file from /tb and run Behavioral Simulation.',
        'View the simulation waveform vectors to verify timing and state transitions.',
      ],
    },
    reviews: [
      {
        id: 'rev-401',
        user: 'Ananya Deshmukh',
        role: 'VLSI System Designer',
        rating: 5,
        date: '2 weeks ago',
        verified: true,
        comment: 'Zero timing violations in Vivado timing summary report! The FSM state diagram and comprehensive testbench made my project evaluation an effortless top grade.',
      },
    ],
    license: 'Academic & Research Digital Logic Design License',
    techStack: ['Verilog HDL', 'VHDL', 'STM32 / ARM', 'ModelSim', 'Vivado / Quartus', 'Xilinx FPGA', 'Keil uVision', 'I2C / SPI'],
  },
  {
    id: 'project5',
    title: 'Automation & Custom Software',
    slug: 'automation-custom-software',
    category: 'Custom Digital Products',
    categorySlug: 'automation-saas',
    tagline: 'Custom workflow tools, automated scrapers & enterprise systems.',
    handwritingNote: 'Turn manual workflows into automated, high-speed machines.',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    company: 'Homies Creator Studio',
    liveLink: undefined,
    price: 2799,
    originalPrice: 5499,
    rating: 4.93,
    reviewCount: 31,
    salesCount: 128,
    difficulty: 'Intermediate',
    projectType: 'Automation Suite',
    platform: 'Cloud Server / Docker / CLI / Web',
    language: 'Python / Node.js',
    isFeatured: false,
    isBestSeller: true,
    isTrending: false,
    creator: {
      name: 'Homies Automation & Cloud Studio',
      handle: '@homies_ops',
      role: 'Senior Cloud Automation Architect',
      rating: 4.94,
      sales: 390,
      avatar: '/homies/header-logo.png',
      responseTime: '< 2 hours',
      badges: ['Automation Pro', 'Dockerized', 'High Reliability'],
    },
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Custom automation systems, workflow scrapers, data pipelines, and specialized digital products built around real-world requirements.',
      'End-to-end development tailored for startups, individual builders, and business operational efficiency.',
      'Scalable architecture designed for high availability, security, scheduled background workers, and automated notifications.',
    ],
    whyHomies: [
      'Tailor-made software built strictly around your specific problem — no bloated, generic templates.',
      'Robust error handling, background retries, and comprehensive activity logging for rock-solid reliability.',
      'Frictionless deployment with clean Docker containers and automated one-click execution scripts.',
    ],
    whatMakesUsSpecial: [
      'High-speed data harvesting, bots, and API connectors engineered for heavy throughput without rate limits.',
      'Interactive control dashboards and instant alert integrations (WhatsApp, Telegram, Email, Slack).',
      'Clean modular architecture that makes future feature additions painless.',
      'Post-delivery onboarding walkthroughs and continuous technical support.',
    ],
    deliverables: [
      'Production-Ready Source Code & Environment Configs',
      'Interactive Web Management Dashboard (FastAPI / Streamlit / React)',
      'Docker Compose Multi-Container Orchestration & Deployment Guide',
      'Full API Documentation, Postman Collections & System Walkthrough',
    ],
    deliverableFiles: [
      { name: 'Complete Automation Source Code (ZIP)', size: '21.3 MB', type: 'code' },
      { name: 'Docker Compose & Kubernetes Manifests', size: '1.2 MB', type: 'code' },
      { name: 'API Schema & Integration Postman Collection', size: '1.8 MB', type: 'doc' },
      { name: 'Operations & Maintenance Manual (PDF)', size: '4.1 MB', type: 'pdf' },
    ],
    requirements: {
      os: 'Windows, macOS, Linux',
      software: 'Python 3.10+, Docker & Docker Compose, Git',
      hardware: '2 GB RAM, 1 GB disk space',
      dependencies: 'FastAPI, Playwright, Celery, Redis, SQLAlchemy, PostgreSQL',
      installationSteps: [
        'Navigate to the project root directory.',
        'Copy .env.example to .env and configure your secret keys and database URLs.',
        'Run with Docker: docker-compose up -d --build',
        'Or run locally: pip install -r requirements.txt && python main.py',
      ],
    },
    reviews: [
      {
        id: 'rev-501',
        user: 'Tariq Al-Mansoor',
        role: 'Operations Director',
        rating: 5,
        date: '3 weeks ago',
        verified: true,
        comment: 'Replaced 15 hours of weekly manual data entry with a single scheduled worker. Flawless execution and super clean documentation.',
      },
    ],
    license: 'Commercial Operational Automation License',
    techStack: ['Python', 'FastAPI', 'Node.js', 'PostgreSQL', 'Docker', 'Redis', 'Selenium / Playwright', 'Cloud Functions'],
  },
];

export default projects;
